name: Run Headless Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  headless-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Run tests in headless mode
        run: ./gradlew test -Dheadless=true

      - name: Generate Allure Report
        run: ./gradlew allureReport

      - name: Upload Allure Report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: build/reports/allure-report
