name: Run Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      env:
        description: 'Test environment'
        required: true
        default: 'qa'
        type: choice
        options:
          - dev
          - qa
          - staging
      browser:
        description: 'Browser to run tests'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox

jobs:
  Run-Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Run tests in headless mode
        run: |
          ./gradlew clean test -Dheadless=true -Denv=${{ github.event.inputs.env }} -Dbrowser=${{ github.event.inputs.browser }}
        continue-on-error: true

      - name: Generate Allure Report
        run: |
          ./gradlew allureReport || true
          cp -r build/reports/allure-report/* ./
          touch .nojekyll

      - name: Deploy Allure Report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: .
          clean: true
          single-commit: true